import Sdl.Core.Macros
import Sdl.Error
import Sdl.Init
import Sdl.Properties
import Sdl.Hints
import Sdl.Log
import Sdl.Timer
import Sdl.Guid
import Sdl.Time
import Sdl.Filesystem
import Sdl.CpuInfo
import Sdl.Power
import Sdl.Locale
import Sdl.Misc
import Sdl.Rect
import Sdl.BlendMode
import Sdl.Pixels
import Sdl.IOStream
import Sdl.Surface
import Sdl.Video
import Sdl.Clipboard
import Sdl.MessageBox
import Sdl.Scancode
import Sdl.Keycode
import Sdl.Keyboard
import Sdl.Mouse
import Sdl.Touch
import Sdl.Pen
import Sdl.Events
import Sdl.Dialog
import Sdl.Audio
import Sdl.Sensor
import Sdl.Camera
import Sdl.Joystick
import Sdl.Gamepad
import Sdl.Haptic
import Sdl.Render
import Sdl.AsyncIO
import Sdl.Storage
import Sdl.Process
import Sdl.LoadSo
import Sdl.System
import Sdl.Tray
import Sdl.Gpu
import Sdl.Gpu.Pipeline
import Sdl.App

/-!
Root module of the `Sdl` library: Lean 4 FFI bindings for SDL3.
-/
